### PR TITLE
remove wrong isset in shouldLog

### PR DESCRIPTION
**Pull request by tiemevanveen**
Shouldn't this not be `isset` but just checking the value? 

Changing this is failing your tests btw 😬 . Did I find a bug 🐞  ?

### CODE REVIEW

**Comment by tiemevanveen** [comment]
Oh wait, no you're right, you're just checking if the option is set, not if the option is set and is true. But in that case, you don't need one of the 2 checks right? I'm removing the 2nd one in another commit, hold on.

**Comment by SpacePossum** [comment]
Thing is if `$app[$name.'.enable_log']` is `'no'` it would now pass and add the logger.
I agree that this test is maybe too strict and holds no real value. In any closed env. project I would merge this in a heartbeat. However since this is part of the public interface of the service it would be a BC break and for a small gain (again I would accept it in a closed project). Therefor I cannot accept it on the release branch, but I consider picking your commit on master (or I retarget your PR to master).

**Comment by tiemevanveen** [comment]
I don't think this PR changes the functionality. 

```
Isset(x) === ( true === isset(x) ) 
```

Right? So you can remove one of the 2 checks. 

I would indeed not only merge the first commit. But I think both combined (removing the 2nd check) is fine.

**Comment by SpacePossum** [comment]
Ah check, it is a typo I made so this can go in indeed :)

Current
```php
isset($app[$name.'.enable_log'])
true === isset($app[$name.'.enable_log'])
```

What I meant:
```php
 isset($app[$name.'.enable_log'])
true === $app[$name.'.enable_log']
```

:+1:

**Comment by tiemevanveen** [comment]
Check 😉

On 30 sep. 2016, at 10:10, SpacePossum <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah check, it is a typo I made so this can go in indeed :)

Current

isset($app[$name.'.enable_log'])
true === isset($app[$name.'.enable_log'])

What I meant:

 isset($app[$name.'.enable_log'])
true === $app[$name.'.enable_log']

👍

**Comment by SpacePossum** [comment]
Thnk you @tiemevanveen

**Pull request merged**
