### PR TITLE
WIP - Add tests that use real memcached server

### PR DESCRIPTION
**Pull request by tiemevanveen**
run Travis run!

### CODE REVIEW

**Comment by SpacePossum** [comment]
Are you planning on finishing this with real tests?

**Comment by tiemevanveen** [comment]
I'll see what I can do tonight.

**Comment by tiemevanveen** [comment]
I'm afraid it [looks like](https://travis-ci.org/GeckoPackages/GeckoSilexMemcacheService/builds/128958837) Travis also runs a not supported Memcached version. I've changed the travis file to look further into this but travis [stopped](https://travis-ci.org/GeckoPackages/GeckoSilexMemcacheService/pull_requests) doing the checks. I think I spammed it too much..  Will check back later when tests are finished.

**Comment by tiemevanveen** [comment]
Finally done.

Travis is running:
* memcached.so [v2.2.0](https://pecl.php.net/package/memcached/2.2.0) (stable)
* libmemcached [v1.0.18](https://launchpad.net/libmemcached/1.0/1.0.18) (stable) 
* memcached v1.4.13 (a bit behind but who cares :p) 

Which is all stable so the tests should not fail right? 

Lets see if I can fix this: :).. 
```
1) MemcachedLoggingCompletenessTest::testMethodLogging
Declaration of GeckoPackages\Silex\Services\Caching\Clients\MemcachedLogging::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)
```

**Comment by tiemevanveen** [comment]
> Lets see if I can fix this: :)..

Oh wait, that was the same issue as we've found here: 
https://github.com/GeckoPackages/GeckoSilexMemcacheService/issues/6

Hmm. Ok.. we first have to solve that. I'll add a comment on that issue.

**Comment by SpacePossum** [comment]
Proxy/mocking issue has been resolved. 
However I still feel that if there should be real testing with memcache it should be at the mock (i.e. checking if test ran on the mock yield the same results as on the real thing), but not here. The service provider is about interfacing between a (Silex/Pimple) application and the memcache(d) extension and/or mock and not about interacting directly with server (so we should not need the server in the tests).

Thanks for looking into this and the work done on it, it helped a lot to get the mock in shape and getting the proxy class setup :+1: :)

**Comment by tiemevanveen** [comment]
> The service provider is about interfacing between a (Silex/Pimple) application and the memcache(d) extension and/or mock and not about interacting directly with server (so we should not need the server in the tests).

Yeah you're right. But then you need the mock to be rock solid. In indeed also do:

> i.e. checking if test ran on the mock yield the same results as on the real thing

Good to hear the pr at least helped you a bit :)

**Pull request closed without merging**
