### PR TITLE
[WIP] Fix logger

### PR DESCRIPTION
**Pull request by SpacePossum**

### CODE REVIEW

**Comment by SpacePossum** [comment]
note to self, do not conflict ext-memcached 1 line on 1.x branch, check the version of the ext. in `shouldLog` method

**Comment by tiemevanveen** [comment]
aabtestdffg😁

**Comment by SpacePossum** [comment]
https://github.com/GeckoPackages/GeckoSilexGearmanService/pull/2  :(
and Ive already squashed that one a few times haha

**Comment by SpacePossum** [comment]
closing in fav. of https://github.com/GeckoPackages/GeckoSilexMemcacheService/pull/12

**Pull request closed without merging**
